ruby-china/homeland

app/assets/javascripts/notes.coffee
Modify NodeView to NoteView
visit https://ruby-china.org/notes/new
console:
`Uncaught ReferenceError: NoteView is not defined`
=> Fix NoteView is not defined

app/helpers/topics_helper.rb
=> fix syntax

app/views/layouts/application.html.erb
As per discussion in https://github.com/ruby-china/ruby-china/pull/360#discussion_r19424427.
cc @lgn21st 
Ref. https://developers.google.com/analytics/devguides/collection/analyticsjs/display-features
=> Enable Display Features for Google Analytics.

app/views/shared/_editor_help_block.html.erb
=> 修复格式说明无法弹出问题

app/views/cpanel/replies/_form.html.erb, app/views/cpanel/topics/_form.html.erb
=> remove unused inputs in Topic, Reply form. (refer commit 4aa5dc91)

app/models/node.rb, app/views/topics/_sidebar_for_topic_index.html.erb, spec/models/node_spec.rb
另，发现一个奇怪的现象，原本打算使用 `where(:_id.in => node_ids).limit(5)`，但发现这样写，测试 `expect(Node.new_topic_dropdowns.length).to eq(5)` 过不了。会报：`expected: 5 got: 10` 的错。
=> 减少 View 中的逻辑，将`发布新贴`旁下拉 Node 列表抽取到 Model 中

app/assets/javascripts/topics.coffee
=> fix #319 图片放大的时候，一旦滑动鼠标一大片白底就露出来了

Gemfile.lock, app/views/topics/_sidebar_box_node_recent_topics.html.erb
这个bundle, 提交者应该升级到1.9.9, 就不会出现bundled with这个东西了
=> 节点下的其它话题，保证不包含该话题自身

config/routes.rb
=> require sidekiq right before its use

config/unicorn.rb
https://github.com/SamSaffron/message_bus
=> 按照 message_bus 官方的说明，修改 Unicorn 的配置;

app/models/reply.rb, app/views/replies/create.js.erb, spec/models/reply_spec.rb
=> 回帖内容里面包含 +1, :plus1: 等赞有关的字符时，赞帖子

README.md
[View Rendered README.md](https://github.com/JuanitoFatas/ruby-china/blob/a277759d4b74293f8f0b620030a9d931dc8ce81d/README.md).
=> Update travis badge to SVG format [ci skip]

app/api/v3/root.rb, app/api/v3/topics.rb, app/controllers/topics_controller.rb, app/helpers/users_helper.rb, app/models/topic.rb, app/models/user.rb, app/serializers/topic_detail_serializer.rb, app/serializers/topic_serializer.rb, app/serializers/user_detail_serializer.rb, spec/api/nodes_spec.rb, spec/api/topics_spec.rb, spec/api/users_spec.rb, spec/models/topic_spec.rb, spec/models/user_spec.rb
按 ruby-china/ruby-china-app 的实际需求增加 API 字段。
@dothide
=> Add more fields for User API

Gemfile, Gemfile.lock
https://github.com/ASoftCo/leaky-gems
=> Upgrade memory leaks gems

config/locales/en.yml, config/locales/menu.en.yml
=> Add some English translations

bin/setup
=> fixed setup syntax error

app/controllers/search_controller.rb
Use simple_query_string to avoid exception
=> Use simple_query_string for search

app/controllers/sessions_controller.rb
=> Fix captcha invalid i18n message

app/views/topics/translation/_need_login_to_reply.zh-CN.html.erb
1. Issue from ruby-china, https://ruby-china.org/topics/28783 .
2. Refer to  https://github.com/ruby-china/ruby-china/blob/master/app/views/topics/translation/_need_login_to_reply.zh-TW.html.erb#L3
=> Upgrade need login to reply's chinese message

.travis.yml, bin/provision.sh, bin/setup, config/database.yml.default
* 去掉mongo
* 安装postgresql
* 创建用户 admin 密码admin
=> 更新vagrant脚本

lib/markdown.rb, spec/lib/markdown_spec.rb
=> Upgrade @user match regexp for medium link

bin/provision.sh, config/database.yml.default
* host 指定localhost
* libpq-dev
=> 修复vagrant环境setup脚本跑不通

app/controllers/replies_controller.rb, app/views/replies/create.js.erb, spec/controllers/replies_controller_spec.rb
=> Bug Fix: topic's replies_count doesn't change after replied

app/controllers/sessions_controller.rb, spec/controllers/sessions_controller_spec.rb
=> Skip referrer cache if it's from other site

app/models/reply.rb, spec/models/topic_spec.rb
修复编辑/喜欢回复的时候帖子会被顶上。
其他测试在我 Pull 下来时就有通不过的，应该另外修复。
=> Use after_create to touch topic last active mark

app/views/notes/index.html.erb, app/views/notifications/index.html.erb, app/views/search/index.html.erb, app/views/users/blocked.html.erb, app/views/users/city.html.erb, app/views/users/favorites.html.erb, app/views/users/followers.html.erb, app/views/users/notes.html.erb, app/views/users/replies.html.erb, app/views/users/topics.html.erb
=> Add clearfix class to panel footer pagination

app/assets/javascripts/app.coffee, app/views/layouts/application.html.erb, config/routes.rb
action cable 默认mount位置是 "/cable", 使用helper设置，只需要维护一个地方，如果mount的url有变化的话 改 config.action_cable.mount_path 就行了，不用改两个地方
https://github.com/rails/rails/blob/master/actioncable%2Flib%2Faction_cable%2Fhelpers%2Faction_cable_helper.rb#L31
=> use action cable helper to set action cable mount url

app/assets/stylesheets/cal-heatmap.scss, app/assets/stylesheets/front.scss, app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/models/user.rb, app/views/users/_info.html.erb, config/routes.rb, spec/controllers/users_controller_spec.rb, spec/models/user_spec.rb
=> Feature user activity graph

bin/provision.sh, db/schema.rb
- Fix Vagrant provision script
- Fix schema.rb
=> Fix dev environment

app/controllers/sessions_controller.rb, spec/controllers/sessions_controller_spec.rb
=> update user_return_to cacher

app/channels/application_cable/connection.rb, app/controllers/admin/sites_controller.rb, app/controllers/api/v3/application_controller.rb, app/controllers/api/v3/likes_controller.rb, app/controllers/api/v3/nodes_controller.rb, app/controllers/api/v3/notifications_controller.rb, app/controllers/api/v3/replies_controller.rb, app/controllers/api/v3/topics_controller.rb, app/controllers/api/v3/users_controller.rb, app/controllers/application_controller.rb, app/controllers/replies_controller.rb, app/controllers/search_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/helpers/likes_helper.rb, app/helpers/topics_helper.rb, app/helpers/users_helper.rb, app/jobs/push_job.rb, app/jobs/search_indexer.rb, app/mailers/user_mailer.rb, app/models/concerns/base_model.rb, app/models/concerns/mentionable.rb, app/models/location.rb, app/models/note.rb, app/models/notification.rb, app/models/reply.rb, app/models/topic.rb, app/models/user.rb, app/models/user/omniauth_callbacks.rb, app/uploaders/base_uploader.rb
Hey @huacnlee ,
主要根据 rubocop 提示，review please
=> fix code style issue

app/controllers/account_controller.rb, app/controllers/sessions_controller.rb
=> Fix  the redirect url issue after user profile updated

app/assets/javascripts/app.coffee
=> fix md_emoji js auto compelte bug

config/routes.rb, spec/routing/users_routing_spec.rb
=> fix dot in username caused router error

app/controllers/topics_controller.rb, app/views/topics/_form.html.erb
=> hot fix for topic create missing node select bug

app/controllers/topics_controller.rb, app/models/topic.rb, app/models/user.rb, app/views/topics/index.html.erb
看过 rails 的 cache key 生成代码，觉得添加个 ActiveRecord::Relation 的 case 比较方便。
``` ruby
def expanded_key(key) # :nodoc:
return key.cache_key.to_s if key.respond_to?(:cache_key)
case key
when Array
if key.size > 1
key = key.collect{|element| expanded_key(element)}
else
key = key.first
end
when Hash
key = key.sort_by { |k,_| k.to_s }.collect{|k,v| "#{k}=#{v}"}
end
key.to_param
end
```
=> refactor TopicsController's index action

app/views/layouts/application.html.erb
用 meta tag 传递用户信息到客户端。这是 Basecamp 3 的用法。
=> Add current-user meta tag

Vagrantfile, bin/provision.sh
- 用 PPA 安装新版本 redis，不然 redis-search 的 zadd 会报异常
- 增加虚拟机内存
=> fix vagrant config, upgrade redies version and memory size

app/controllers/users_controller.rb, app/views/users/city.html.erb
=> update user list by city page's city title

app/assets/stylesheets/admin.scss
原来admin bar的left padding太大，一行都显示不下。。
=> nice admin nav bar.

app/models/user.rb
=> user check method with rails self

app/models/user.rb, app/models/user/blockable.rb, app/models/user/followable.rb, app/models/user/github_repository.rb, app/models/user/likeable.rb, app/models/user/topic_favorate.rb, app/models/user/topic_read.rb
=> refactor user model with domain module

app/assets/javascripts/app.coffee, app/assets/stylesheets/application.scss, config/initializers/social_share_button.rb, config/locales/social_share_button.en.yml, config/locales/social_share_button.zh-CN.yml, config/locales/social_share_button.zh-TW.yml
依赖新版 social_share_button 的微信功能
=> add weixin share button

README.md
=> Should import the model one by one, import all not working

Gemfile, Gemfile.lock, app/views/search/index.html.erb, config/initializers/elasticsearch.rb
之前的实现如果Team被搜索到是无法显示的，会直接报错，STI的关系目前可以作为user来处理。
https://github.com/elastic/elasticsearch-rails/issues/619
=> Allow search Team class as user.

app/views/account/edit.html.erb, app/views/teams/edit.html.erb
Update on account edit page and team edit page:
=> Use https for twitter URLs

config/config.yml.default, config/environments/production.rb
让 ActionMailer 配置支持通过 config.yml 任意配置
=> 让 ActionMailer 配置支持通过 config.yml 任意配置

CONTRIBUTE.md, Gemfile, Gemfile.lock, app/controllers/search_controller.rb, app/models/user.rb, app/views/search/_team.html.erb, app/views/search/_user.html.erb, app/views/search/index.html.erb, config/initializers/elasticsearch.rb, config/initializers/redis.rb, spec/controllers/search_controller_spec.rb
不需要用 elasticsearch-rails gem 的 master 代码，验证了 Team, User 继承方式搜索没有问题; #768
=> 改进搜索，采用 ElasticSearch 的 prefix query 功能代替 redis-search

config/locales/users.zh-CN.yml, config/locales/users.zh-TW.yml
=> 文案修正，登陆->登录 #33

app/assets/javascripts/topics.coffee, app/assets/stylesheets/application.scss, app/assets/stylesheets/front.scss, app/controllers/replies_controller.rb, app/models/ability.rb, app/models/concerns/mentionable.rb, app/models/reply.rb, app/views/replies/_reply.html.erb, app/views/replies/_reply_to.html.erb, app/views/replies/reply_to.js.erb, app/views/shared/_editor_toolbar.html.erb, app/views/topics/_reply_form.html.erb, app/views/topics/_topic.html.erb, config/environments/development.rb, config/routes.rb, db/migrate/20170222062457_add_reply_to_id_to_replies.rb, db/schema.rb, spec/controllers/replies_controller_spec.rb, spec/models/concerns/mentionable_spec.rb, spec/models/reply_spec.rb
=> 新功能 In Reply To

db/migrate/20170207141208_remove_array_action_fields.rb
=> [WIP] Remove old Array fields, they were instead by ActionStore.

app/views/layouts/simple.html.erb
修正 app/views/layouts/simple.html.erb 没有从配置里读取 brand name
=> fixed #873, remove ruby china.

Gemfile, Gemfile.lock, PLUGIN_DEV.md, app/assets/stylesheets/front.scss, app/controllers/application_controller.rb, app/controllers/likes_controller.rb, app/helpers/likes_helper.rb, app/views/shared/_navbar.html.erb, app/views/shared/_usernav.html.erb, db/schema.rb, lib/homeland.rb, lib/homeland/plugin.rb, spec/controllers/team_users_controller_spec.rb, spec/helpers/likes_helper_spec.rb, spec/lib/plugin_spec.rb, spec/rails_helper.rb
1. 新增插件有关的几个函数，以便于插件可以在导航栏、用户菜单显示
2. 新增插件开发的文档
=> 新增插件有关的几个函数，以便于插件可以在导航栏、用户菜单显示

app/assets/javascripts/topics.coffee
=> fix: resubscribe when topic change

app/models/comment.rb, app/models/concerns/user_avatar_delegate.rb, app/models/reply.rb, app/models/topic.rb, app/uploaders/avatar_uploader.rb, app/uploaders/photo_uploader.rb, app/views/notifications/notifications/_notification.html.erb, app/views/replies/_reply.html.erb, app/views/settings/show.html.erb, app/views/topics/_topic.html.erb, app/views/topics/show.html.erb
=> 重构用户头像的 URL 地址，采用每次用新的文件名

config/routes.rb, spec/routing/users_routing_spec.rb
解决 admin 下面编辑用户名类似(xiao.ming)，会出现类似无法提交更新的情况。
=> admin user should also has constraint

public/404.html
fixed Chrome: This page is trying to load scripts from unauthenticated sources, 尽管很多人也连不到.
=> fixed Chrome: This page is trying to load scripts alert

app/controllers/api/v3/topics_controller.rb, app/views/api/v3/application/_reply.json.jbuilder, app/views/api/v3/topics/replies.json.jbuilder
详细内容见 https://ruby-china.org/topics/33016
=> 修复API文档一处小错误；另外在获取话题的回帖列表时，返回回帖的详细内容

app/controllers/api/v3/users_controller.rb
=> 修改 API 文档一处小错误，此处应该返回的是用户列表而不是话题列表

app/controllers/auth/omniauth_callbacks_controller.rb
env to request.env to avoid github login failure
=> env to request.env to avoid github login failure

app/views/settings/account.html.erb
It seems that there should one more closing div tag for account.html.erb.
=> Add a missing close tag for account.html.erb

app/controllers/topics_controller.rb
删除 `TopicsController` 里面的before_action 多余的 `ban`。
=> remove duplicate entry in before_action

app/views/topics/feed.builder, config/application.rb, config/environments/production.rb, config/initializers/session_store.rb, spec/controllers/admin/comments_controller_spec.rb, spec/controllers/search_controller_spec.rb, spec/models/ability_spec.rb
Auto corrected by following Space
Click [here](https://awesomecode.io/projects/50/ruby_config_groups/494) to configure it on awesomecode.io
=> Auto corrected by following Space

app/views/admin/nodes/index.html.erb
https://github.com/ruby-china/homeland-docker/issues/37
=> Fix admin/nodelist error when section nil

app/views/account/new.html.erb
https://github.com/ruby-china/homeland/issues/1021
=> 修正注册表单，账号应该用普通文本框

app/controllers/admin/users_controller.rb, app/controllers/topics_controller.rb, app/helpers/users_helper.rb, app/models/setting.rb, app/models/topic.rb, app/models/topic/rate_limit.rb, app/views/admin/users/edit.html.erb, config/config.yml.default, config/locales/menu.zh-CN.yml, spec/models/topic_spec.rb, spec/rails_helper.rb
=> 新增话题创建的频率限制功能

app/assets/stylesheets/front.scss
https://l.ruby-china.org/photo/2018/2ac3c224-156e-47d1-abb2-9938303f3472.png!large
修复发表帖子预览编辑时文字溢出问题
=> fix overflow in markdown preview

app/assets/stylesheets/application.scss
=> 修复 navbar 遮挡 modal 的问题

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss
https://github.com/antirez/redis/issues/4272
=> 使用小于 4.0 版本的 redis gem

app/views/settings/account.html.erb
- 不在想 -> 不想
- 登陆 -> 登录
- ✂️ blank lines
=> Improve copy at account settings page

.travis.yml
更新 travis-ci 使用 Gemfile.lock 的 remote
=> Fix .travis.yml Gemfile.lock remote & db create

app/views/admin/sections/_form.html.erb
=> 后台分类维护界面显示两个名称

app/controllers/users/user_actions.rb
=> follow/unfollow 后应该reload一下数据，否则页面上的关注者数据显示不准确

config/locales/topics.en.yml, config/locales/topics.zh-CN.yml, config/locales/topics.zh-TW.yml
https://ruby-china.org/topics/favorites
意外發現少了翻譯，就順手補上了
=> fix(Locale/Topic): 加上 favorites 我的收藏的翻譯

app/views/replies/edit.html.erb
form 的 attribute 没有 render 出来， javascript 未执行
=> fix form html attribute

Gemfile.lock, app/models/reply.rb, app/models/setting.rb, spec/models/reply_spec.rb, spec/models/setting_spec.rb
=> Fix array setting keys store

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/models/topic/auto_correct.rb, config/environments/development.rb, lib/homeland/markdown.rb, lib/homeland/pipeline/auto_correct_filter.rb, spec/fixtures/markdown/out.html.txt, spec/fixtures/markdown/raw.md, spec/lib/markdown_spec.rb
https://github.com/huacnlee/auto-correct
=> 引入 AutoCorrect，并对正文实现自动中英文排版格式化

lib/homeland/pipeline/embed_video_filter.rb
=> add bilibili filter

db/migrate/20200213155459_add_unique_index_to_users.rb, db/schema.rb
关于老的实现，实际上之前是有逻辑的唯一验证确保 login, email 不重复，但极限场景有可能重复。
=> HOTFIX: 确保用户的 login, email 是唯一的，并增加 Migration 修正老数据。

app/views/admin/dashboards/index.html.erb
https://github.com/ruby-china/homeland-docker/issues/51
=> Remove Note stats in admin dashboard for fix #51

test/uploaders/avatar_uploader_test.rb, test/uploaders/photo_uploader_test.rb
Fix uploaders test `svg_image` variable
No
No
=> test: Fix uploader test svg_image variable

app/controllers/photos_controller.rb, app/javascript/front/editor.js, test/controllers/photos_controller_test.rb
=>  hotfix: Fix message issue while uploading the images.

app/views/settings/account.html.erb
=>  hotfix: fix icon missing issue.

app/javascript/front/topics.js, app/views/sessions/new.html.erb
Feedback from https://ruby-china.org/topics/40317
=>  hotfix: fix height issue in preview box.

app/controllers/users_controller.rb
=> fix: users can unfollow users who has deleted

app/javascript/front/app.js, app/javascript/front/index.scss, app/javascript/homeland/dark-mode.scss, app/javascript/homeland/index.scss, app/views/shared/_usernav.html.erb, config/locales/menu.en.yml, config/locales/menu.zh-CN.yml, config/locales/menu.zh-TW.yml
=> Add switch for dark mode

app/javascript/admin/index.scss
=> Fix admin navbar style

app/javascript/homeland/index.scss
=> Logo font same as body.

app/javascript/homeland/index.scss
=> Fix font, better for Windows

app/javascript/homeland/dark-mode.scss
=> Fix dark mode css for .btn-move-page

app/controllers/admin/topics_controller.rb, app/controllers/api/v3/topics_controller.rb, app/controllers/topics_controller.rb, app/helpers/topics_helper.rb, app/models/topic.rb, app/views/admin/topics/index.html.erb, app/views/api/v3/application/_topic.json.jbuilder, app/views/notifications/_node_changed.html.erb, app/views/topics/_topic.html.erb, app/views/topics/_topic_info.html.erb, app/views/topics/node_feed.builder, app/views/topics/show.html.erb, db/migrate/20201119010515_remove_node_name_from_topics.rb, db/schema.rb, public/packs-test/manifest.json, test/helpers/topics_helper_test.rb, test/models/topic_test.rb
=> Fix change node name do not sync to topic's node_name

Gemfile, Gemfile.lock, app/models/application_record.rb, app/models/concerns/counterable.rb, config/initializers/redis.rb, test/models/concerns/counterable_test.rb
Remove:
- redis-objects
- redis-namespace
=> Remove redis-objects by implement counter by self.

config/locales/views.zh-CN.yml
=> typo: 登陆 -> 登录

Dockerfile, app/controllers/settings_controller.rb, app/models/profile.rb, app/models/user/profile_fields.rb, app/models/user/reward_fields.rb, app/views/settings/profile.html.erb, app/views/settings/reward.html.erb, app/views/users/_reward.html.erb, db/migrate/20210409032709_upgrade_profile_fields_into_store.rb, db/schema.rb, test/controllers/settings_controller_test.rb, test/models/profile_test.rb, test/models/user/profile_fields_test.rb, test/models/user/reward_fields_test.rb
Upgrade profile.contacts, profile.rewards as JSON type store.
This changes will auto convert old YAML value into JSON value in migration.
Before:
```
"---\n:alipay: https://l.ruby-china.com/photo/2017/7aec944b9a6528c08450f2a6da71b6e9.jpg\n:wechat: https://l.ruby-china.com/photo/2017/68c75e58182bb4ff1d23d67869e4903a.jpg\n"
```
After
```
{"alipay": "https://l.ruby-china.com/photo/2017/7aec944b9a6528c08450f2a6da71b6e9.jpg", "wechat": "https://l.ruby-china.com/photo/2017/68c75e58182bb4ff1d23d67869e4903a.jpg"}
```
=> BREAKING CHANGES: Upgrade profile.contacts, profile.rewards as JSON type store.

app/javascript/front/users.scss
=> Fix follow info text overflow

app/components/reply_component.rb, app/models/concerns/soft_delete.rb, app/views/replies/_create_callback.js.erb, public/packs-test/manifest.json
1. 修复回复序号不从 1 开始的问题
2. 修复发表新回复后序号不正确的问题（特别是当之前的回复有被删除的时候）
3. 暂时没有找到线上有的帖子里回复序号会重复的问题（
=> Fix the wrong floor for replies

app/javascript/front.scss, app/javascript/homeland/application.tailwind.css, package.json, postcss.config.js, tailwind.config.js, yarn.lock
A lot of work to do, this is first step.
=> Start to migrate to TailwindCSS. [WIP]

app/views/topics/_sidebar_for_topic_index.html.erb, config/locales/views.en.yml, config/locales/views.zh-CN.yml, tailwind.config.js
- 优化 ActiveUsersCard 界面，让头像昵称剧中，优化间距尺寸。
Ref #1335
=> Tailwind CSS 不用前缀的方式，直接使用。

test/helpers/likes_helper_test.rb
=> Modify test file to fix default title display for likes

app/controllers/topics_controller.rb, app/controllers/users/user_actions.rb, app/controllers/users_controller.rb, app/models/counter.rb, app/views/topics/_references.html.erb, app/views/users/_sidebar.html.erb, test/integration/users_test.rb
Even the integration test can not find it, so remove maybe a temp solution.
I still can not find a proper way to testing load_async
=> load_async still got error after Rails 7.1.3

.env, test/models/user_test.rb
https://ruby-china.org/topics/43688
奇怪，这么测试未发现有问题
=> Add test for User#login special case.

package.json, yarn.lock
Reverts ruby-china/homeland#1414
=> Revert "Need downgrade to 5.2.3 because 5.3 introduce .card-body color"

app/javascript/homeland/dark-mode.scss, app/views/users/index.html.erb
=> Fix missed bootstrap var in dark mode.
