- app/assets/stylesheets/application.scss
- app/views/home/index.html.erb
修复小屏幕尺寸下的响应式细节，问题如：
然后重现：
修复后结果：
大屏幕下不影响正常样式：
> Add dividing line between best articles

- app/assets/javascripts/jquery.hotkeys.js
- app/assets/javascripts/topics.coffee
增加文本编辑器中 tab 按键事件的处理，自动插入两个空白字符
加入 tab 事件处理的原因：一个是更符合文本编辑器的使用习惯，另一个是避免还没编辑完的内容因为 tab 默认将输入焦点跳动到了提交按钮，此时不小心按下回车会导致内容被提交。
> Support tab in the text editor

- app/models/topic.rb
另外直接在这里写 auto_correct_title 是不是不大好? 我去翻了下 auto-space gem, 觉得可以把自动替换这部分加入到 auto-correct 中, 我在你的另一项目 auto-correct 中 pull request 了一点想法, 目前 auto-space 功能略单一, 把功能相近的自动替换一起整合进 auto-correct 中会不会好一些?
> 替换标题里面的全部中文中括号和括号到英文, sub -> gsub

- config/application.rb
可以让第三方通过 grant_type=password 方式在前端直接 post form 表单到 `https://ruby-china.org/oauth/token` 获取到合适的 token 并且不需要一个中间服务器来处理这个 proxy
如果需要再严苛一点的路由: 
```ruby
config.middleware.use Rack::Cors do
allow do
origins '*'
resource '/api/*', headers: :any, methods: [:get, :post, :put, :delete, :destroy]
resource '/oauth/token', headers: :any, methods: [:post]
end
end
```
> 增加 oauth 的跨域请求

- .gitignore
- lib/markdown.rb
- spec/lib/markdown_spec.rb
@huacnlee @lgn21st @chloerei 
修正markdown中header标题中，包含链接时的，convert的不合适，
> fix markdown h3 contain link bug

- app/views/comments/create.js.erb
现状：如果一篇 wiki 没有回复，当第一条回复提交并显示该回复后，界面上的 【暂无回复】字样并未消失。
预期：如果一篇 wiki 没有回复，当第一条回复提交并显示该回复后，界面上的 【暂无回复】字样应该自动消失
> 修正 wiki 回复后仍显示暂无回复的 BUG

- app/controllers/topics_controller.rb
`check_current_user_status_for_topic` creates thread inside, so it should be invoked before threads join.
> join threads after all threads created in topics#show

- lib/markdown.rb
- spec/lib/markdown_spec.rb
https://ruby-china.org/topics/27458
> 修复代码中 =@xx 高亮被分成 =@ 和 xx 的情况

- app/assets/images/mask.svg
- app/views/layouts/application.html.erb
See
https://developer.apple.com/library/prerelease/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html
> Add 16x16 SVG mask icon for Safari pinned icon.

- app/assets/javascripts/app.coffee
- app/assets/javascripts/topics.coffee
> Fix #430 Reply hotkeys

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- Vagrantfile
- bin/provision.sh
- config/environments/development.rb
方便搭建开发环境，用法：
安装 VirtualBox 
https://www.virtualbox.org/
安装 Vagrant
https://www.vagrantup.com/
进入项目目录，然后:
```console
$ vagrant up
$ vagrant ssh
$ cd /vagrant
/vagrant $ ./bin/setup
/vagrant $ rails s -b 0.0.0.0
```
`vagrant up` 首次执行要下载系统镜像、安装系统依赖，根据网速不同可能要半个多小时。
然后在主机打开 localhost:3000 访问。在主机用任意编辑器编辑，修改会自动同步到虚拟机里面。
性能方面还有一些问题：
1. config/environments/development.rb 里面的配置 `config.assets.raise_runtime_errors = true` 大概会拖慢 150ms，我觉得可以关掉。
2. VirtualBox 的文件共享会拖慢速度，大概会增加一倍渲染时间，换用 NFS 可以解决。不过 sprockets 不知道什么问题， 3.0+ 版本用 NFS 共享反而会变慢，降到 2.12 就没有问题。暂时不知道怎么解决，如果性能可以接受可以不管。
> 添加 Vagrant 配置

- config/initializers/devise.rb
20 对于在意安全的人来说太短了， 太长可能增加计算负担，所以上限改到 128。
https://twitter.com/lrz/status/653925934274375680
> 把密码长度限制改成 6..128

- app/assets/stylesheets/application.scss
修改以下issue中提到的bug，无需修改turbolinks.js的源码
https://github.com/ruby-china/ruby-china/issues/462
> fix whole page is orange in android wechat and qqbrowser

- app/assets/javascripts/app.coffee
- app/assets/javascripts/google_analytics.js
- app/views/layouts/application.html.erb
把 ga 代码 require 到 app.js 中，这样只会执行一次。把 `ga('send', 'pageview')` 留在 body 就能完成提交统计数据。
另外 mini-profiler 也有这个问题，但它是通过 rack middleware 插入的，还没想到办法处理。
> 修复 Google 统计不断在 head 插入 js 的问题

- app/controllers/notifications_controller.rb
- app/views/notifications/index.html.erb
- config/routes.rb
- spec/controllers/notifications_controller_spec.rb
修改部分rspec，在读取提醒后自动设置为已读。
如未读提醒为较早的话，会出现在后面几页，使得那个未读一直无法清零。有的用户（比如我）不喜欢用清除，反而喜欢留着历史提醒。
> 增加 "未读" 按钮来过滤未读提醒

- app/helpers/topics_helper.rb
- app/models/topic.rb
- app/views/notifications/notification/_topic_reply.erb
- spec/helpers/topics_helper_spec.rb
- spec/models/topic_spec.rb
添加page_floor_of_reply 到topic model里面
添加reply作为topic_title_tag的可选参数，当带有reply时，link将包含#replyXXX
和page，点击link将直接跳到该reply上去。
> 在通知中，点击link会自动跳转到回复的内容

- app/controllers/users_controller.rb
- app/views/users/_sidebar.html.erb
- 同一页访问其他用户 Sidebar 不会变;
- 去掉 /users 页面的 cache，因为 View 上面有和用户有关的 Follow 状态;
> 修正用户主页 Sidebar data-turbolinks-permanent 的问题

- app/models/user.rb
- spec/models/user_spec.rb
如上图，本来想点一下赞自己的帖子的，觉得那个动画效果挺好的，于是狂点了N次，这下好了，从8个赞变成-10个赞了。
> 修复自己重复赞取消赞自己的帖子，赞的数量会一直减1

- config/locales/menu.en.yml
+ https://ruby-china.org/jack8848(I can see "translation missing: en.common.blocked_user")
+ blocked user has no translate key in English language.
> Translate missing

- app/assets/javascripts/app.coffee
- app/assets/javascripts/topics.coffee
- app/assets/stylesheets/application.scss
- app/controllers/topics_controller.rb
- app/helpers/likes_helper.rb
- app/helpers/topics_helper.rb
- app/models/reply.rb
- app/models/topic.rb
- app/views/replies/_reply.html.erb
- app/views/topics/_topic_sidebar.html.erb
- app/views/topics/show.html.erb
- config/environments/development.rb
- spec/controllers/topics_controller_spec.rb
- spec/helpers/likes_helper_spec.rb
- spec/helpers/topics_helper_spec.rb
- spec/models/topic_spec.rb
1. 去掉回复列表的分页，有 Cache 的情况，渲染还是很快的，哪怕有 200 条回复（大部分在 100 一下）
2. 用浮动的工具栏代替之前的话题 Sidebar，如下图
> 去掉回复列表的分页

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- lib/tasks/bundler_audit.rake
- lib/tasks/test_prepare.rake
This Pull Request: 
- Install rest-client 1.8.0
```
Name: rest-client
Version: 1.7.2
Advisory: CVE-2015-1820
Criticality: Unknown
URL: https://github.com/rest-client/rest-client/issues/369
Title: rubygem-rest-client: session fixation vulnerability via Set-Cookie headers in 30x redirection responses
Solution: upgrade to >= 1.8.0
Name: rest-client
Version: 1.7.2
Advisory: CVE-2015-3448
Criticality: Unknown
URL: http://www.osvdb.org/show/osvdb/117461
Title: Rest-Client Gem for Ruby logs password information in plaintext
Solution: upgrade to >= 1.7.3
Vulnerabilities found!
```
- Install turbolinks from secure source and upgrade turbolinks ([CHANGES](https://github.com/rails/turbolinks/compare/83d4b3d...90d4132b))
```
Insecure Source URI found: git://github.com/rails/turbolinks.git
```
- …
> Upgrade rest-client, turbolinks, add bundler-audit, cleanup Rakefile

- app/assets/stylesheets/front.scss
在宽度为 744px - 1200px 之间，右侧的 feed button, 样式显示有问题。
见图：
本次修改后，效果是这样的：
> update feed button style between width 1200px and width 744px

- app/views/topics/_sidebar_for_topic_index.html.erb
> 不能发帖的用户，上传图像后，不应显示 have_no_avatar 消息

- README.md
- Vagrantfile
- bin/provision.sh
- bin/setup
- vagrant provision 添加 elasticsearch。
- vagrant provision 改用 rvm 安装 ruby（2.3 PPA 没有 12.04 的包）。
- elasticsearch 没有把可执行文件放到 path，所以 setup 脚本里面的安装检测用不了。
- setup 漏了个括号。
> Fix vagrant provision and bin/setup script

- config/locales/devise.zh-CN.yml
- config/locales/devise.zh-TW.yml
devise 升级以后 默认写死在 Devise::RegistrationsController里了 可以通过方法覆盖 或者穿scope参数
> fix devise translation

- bin/provision.sh
- bin/setup
- config/database.yml.default
- db/schema.rb
- 简化安装脚本。
- 创建一个有创建删除数据库权限的 pg 用户 vagrant。
- 修复 schema.rb 和 migration 结果不一致。
> 简化 vagrant 安装脚本，修复 db/schema.rb

- app/controllers/cpanel/sites_controller.rb
- app/controllers/cpanel/users_controller.rb
总感觉在 controller 这样直接写 sql 语句不是很好，想抽一个 共有的方法 query 方法到 `ApplicationRecord` 里面。 但是目前只有 2 个地方有 like 查询，所以犹豫和纠结了。
> Fix like query broken bug

- app/views/topics/show.html.erb
原因：在 Topics#show 页面 reply 时， '提交回复' 按钮没有disable，连续点击就会提交多条相同的回复，而且没有提示说明正在提交。
但由于我不明白一行 JS 代码：`$('#reply-button').button('reset')`，
在这行代码后面好像就不能修改`#reply-button`的 text ，在这行前面就可以，
请问是什么意思？这行代码在：[app/assets/javascripts/topics.coffee#L212](https://github.com/ruby-china/ruby-china/blob/master/app/assets/javascripts/topics.coffee#L212)
所以我加的 disable-with 用了 '提交回复' （而不是类似'提交中...'，然后在 Ajax 返回后再替换按钮文字。）
> 在提交时禁用'提交回复'按钮，避免重复提交

- .rubocop.yml
- Gemfile
- Gemfile.lock
升级 rubocop 以便更好的支持 ruby 2.3 特性。
> upgrade rubocop to 0.39.0

- app/helpers/users_helper.rb
- app/views/account/edit.html.erb
- spec/helpers/users_helper_spec.rb
> user_avatar_tag add timestamp option

- app/views/layouts/application.html.erb
今天拿工具扫描了下 Ruby-China 网站，发现有一点点问题：
1. link 没有 color 属性。
2. span 里面不能放 ul。
以下是自定义内容：
链接中间多了个换行符
title 应该为 “本站在.......”
swift.cn 已无法访问，可以除去
> small changes for html dom validator

- lib/markdown.rb
- spec/lib/markdown_spec.rb
> Add responsive to markdown table

- app/views/layouts/simple.html.erb
- simple layout的header中没有`Gems`这一栏
- header上的item没有hover效果（原因是没有使用最新的样式 id="main-nav-menu"）
> fix: simple layout header

- app/controllers/topics_controller.rb
- app/views/topics/_form.html.erb
- app/views/topics/create.js.erb
需要用 xhr 提交表单，不然会导致冷启动。
在 turbolinks-android 下会导致重新打开提交前的页面，不知道 ios 有没有这个问题。
> Use remote form to submit topics for turbolinks-android

- Gemfile
so bundler-audit can not loading if place at dev/test group.
> Capistrano 3 running bundler without dev/test

- app/assets/javascripts/app.coffee
搜索 `test1`, 再搜索 `test2`, 点击浏览器后退按钮即可重现 bug，
如图：
> fix header search input value not match q params bug

- .travis.yml
`ruby-head` will automatically points to latest trunk version of Ruby and allow it to fail.
> Test against trunk Ruby instead

- app/models/location.rb
如果我在 console 中执行, Location.create ,将创建一个 name 为空的记录.
但当访问首页的时候会报错，因为
```
ActionController::UrlGenerationError - No route matches {:action=>"city", :controller=>"users", :id=>""} missing required keys: [:id]:
```
所以我觉得还是给 Location 加个  presence 验证好一点.
> add presence validate for location name

- app/models/page.rb
- app/models/user.rb
- app/views/admin/users/_form.html.erb
- spec/controllers/users_controller_spec.rb
- spec/models/user_spec.rb
代码实现功能：
1. update user state with rails enum.
2. update elasticsearch model index.
一些疑问： 
根据 search_controller/index 的实现：
```ruby
def index
search_params = {
query: {
simple_query_string: {
query: params[:q],
default_operator: 'AND',
minimum_should_match: '70%',
fields: %w(title body name login)
}
},
highlight: {
pre_tags: ['[h]'],
post_tags: ['[/h]'],
fields: { title: {}, body: {}, name: {}, login: {} }
}
}
@result = Elasticsearch::Model.search(search_params, [Topic, User, Page]).paginate(page: params[:page], per_page: 30)
end
```
应该支持用户的搜索，但是在ruby-china 测试，搜索 user login 没有结果，比如 https://ruby-china.org/search?q=small_fish__  
如图：
> refactor user state with rails enum

- Gemfile
- Gemfile.lock
- app/helpers/users_helper.rb
- app/uploaders/base_uploader.rb
- app/views/layouts/application.html.erb
- app/views/layouts/simple.html.erb
- config/config.yml.default
- config/initializers/carrierwave.rb
相关讨论可前往[论坛帖子 Ruby China 有没有可能接受一个阿里云 OSS 的兼容性改动？](https://ruby-china.org/topics/31051)
使用aliyun需要配置相应config.yml，然后在阿里云上[设置图片处理及相关样式](/ruby-china/ruby-china/wiki/Aliyun-OSS-picture-setting)。
这个PR对于现有使用又拍云存贮的ruby-china实例是透明的。
> Add aliyun oss support.

- app/controllers/application_controller.rb
- app/controllers/auth/sso_controller.rb
- app/controllers/sessions_controller.rb
- app/models/setting.rb
- app/models/user.rb
- app/models/user/omniauth_callbacks.rb
- app/models/user_sso.rb
- app/views/pages/_form.html.erb
- config/config.yml.default
- config/environments/production.rb
- config/initializers/inflections.rb
- config/routes.rb
- db/migrate/20161221022846_create_user_sso.rb
- db/schema.rb
- lib/homeland/sso.rb
- lib/homeland/username.rb
- lib/single_sign_on.rb
- spec/controllers/auth/sso_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
- spec/models/setting_spec.rb
- spec/models/user_spec.rb
- 可以支持三方应用提供的 SSO 途径来登录；
- 可以作为 SSO 提供者，为三方应用提供 SSO 登录功能；
- 改进登录后 return_to 的实现细节.
> 实现 Single sign-on 并同时支持用 SSO 登录或作为 SSO Provider.

- app/views/api/v3/application/_reply.json.jbuilder
reply api的返回的json中没有action，这样无法判断一些系统级的回复(关闭话题、加精)。
> refactor: add action column in reply api

- app/models/topic.rb
remove "term_vector", 在生产环境下测试中英文搜索及 rake 正常, 我不确定使用 text 是否比 keyword 会比较好.
ref: https://www.elastic.co/guide/en/elasticsearch/reference/master/text.html
> elasticsearch rebuild Topic error #880

- app/assets/javascripts/app.coffee
- app/assets/javascripts/toc.coffee
- app/assets/stylesheets/front.scss
- app/assets/stylesheets/toc.scss
- app/views/pages/show.html.erb
- app/views/shared/_toc.html.erb
- app/views/topics/show.html.erb
- config/locales/en.yml
- config/locales/zh-CN.yml
- config/locales/zh-TW.yml
> 前端提取标题生成 TOC，支持帖子以及 Wiki 页面

- app/controllers/oauth/applications_controller.rb
- app/views/layouts/simple.html.erb
`layout/simple` was removed in this [commit](https://github.com/ruby-china/homeland/commit/a546c098bd242588e3397e79025af52ced122815), and added back in this [commit](https://github.com/ruby-china/homeland/commit/382c5c430b7171c68739bbbcc826791b60f639bd). But in the second commit, navbar and usernav are missing. So pages for "oauth/applications/*" would look like this:
This PR will bring back navbar, usernav and the page title:
> Bring back navbar and title for oauth pages

- app/views/home/index.html.erb
> fix the sort of excellent_topics in home page

- app/assets/stylesheets/front.scss
- app/views/topics/_node_info.html.erb
[关联PR](https://github.com/ruby-china/homeland-jobs/pull/2)
在插件 Homeland::Jobs 中通过匹配~~热门城市列表和~~招聘板标题的 [城市] 前缀来进一步筛选 @topics 的 scope，在 招聘 栏目的节点信息下方添加一个迷你 filter 来进行城市的筛选。
选择热门城市列表的原因是考虑，在 Ruby China 上某座城市的求职 / 招聘帖的数量和此城市的注册用户数应该是正相关的。
~~路由方面参考了 ruby-china.org/users/city/北京 来进行处理。~~
起因是自己在使用招聘版的时候一直感觉有些不便……当求职者在某个城市求职时，经常会有只想查看这座城市的招聘贴的情况。
初学者中的初学者，如果哪里做的不好或不对还望能不吝赐教一下，万分感谢！
> 招聘页新增一个 filter, 根据城市筛选帖子

- .gitignore
Rails 5.2.0 版本后，需要忽略storage文件夹，因为Active Storage本地保存时，会创建一个storage文件夹。
> 忽略storage文件夹

- app/helpers/application_helper.rb
Someone post a topic with special javascript code in topic title may have serious consequences.
Eg: Create a post with title:
</title><script>alert ('我弹你一下');</script><title> 
Issue #956
> Fixed title_tag xss bug

- app/assets/stylesheets/application.scss
And &.active { @extend .btn-default.active } is not need,
because it already extend .btn-default and will auto extend .btn-default.active
> DEPRECATION WARNING on line 524 of /home/xxxx/homeland/app/assets/stylesheets/application.scss:
Extending a compound selector, .btn-default.active, is deprecated and will not be supported in a future release.
Consider "@extend .btn-default, .active" instead.
See https://github.com/sass/sass/issues/1599 for details.
这个extend不需要声明了，前面已经extend .btn-default了，会自动extend .btn-default的.active,我在浏览器中前后对比了，发现删除这个，生成的css是没有变的，所以我的改动是可行的，并且消除了DEPRECATION WARNING
> Fixed DEPRECATION WARNING about deprecated sass @extend .a.b in application.scss

- app/controllers/topics/list_actions.rb
- app/views/topics/_node_info.html.erb
- app/views/topics/index.html.erb
- config/locales/topics.zh-CN.yml
- config/routes.rb
- spec/controllers/topics_controller_spec.rb
在招聘版下，会调用 Topic 下的 total_pages 逻辑，在招聘相关 topics 不足 1500 （无论是否进行城市筛选）但 topics 总数达到 1500 时，强制列出 60 页分页；点击靠后的分页时，实际并无内容展现。
在 topics 列表页中将判断语句限制为仅在 TopicsController 下才调用 total_pages 逻辑。
一开始的思路是想修改 total_pages 的逻辑使 topics 和 jobs 的分页逻辑分离，但因 jobs 部分本质上还是 Topic 的一个因外挂插件而产生的 scope，如果直接在 Topic 里写死 jobs 的逻辑，对于没有使用 jobs 插件而自己写了其他类似插件的用户，此 bug 依然会复现，问题依然得不到解决；最后选择让 jobs 不调用这条逻辑，但这样又会使招聘版的分页没有底层缓存……不知前辈们对此是否有些更好的思路，若有闲暇还希望能指点一二……
此 bug 为尝试解决以上 bug 时偶然发现的。在 ListAction Module 中的 ban action （筛选已被屏蔽的帖子）与 TopicsController 中的 ban action 产生了命名冲突，从而导致了点击『已屏蔽』按钮时错误调用 TopicsController#ban 的情况。同时『已屏蔽』页面的 title 错误显示为『最新创建』。
将 ListAction 相关的 ban 重命名为 banned，并修改相关路由、页面链接、Locale 以及测试。
Finished in 6 minutes 53 seconds (files took 7.75 seconds to load)
727 examples, 0 failures
> 修复 issue#1055 的分页 bug, 修复已屏蔽主题列表页和屏蔽操作的命名冲突 bug

- config/initializers/redis.rb
According to https://github.com/redis/redis-rb#hiredis, we should pass `driver: :hiredis` as an option if we want to use hiredis.
> Specify redis to use hiredis driver explicit

- config/routes.rb
原因： commit https://github.com/ruby-china/homeland/commit/ecf5543371aaee52663f548535dbe2e7237def88#diff-754caf21f266ab6dc2451900df6c835d 修改了上传文件名为 UUID，文件名中开始有了横线，URL 做图路由不匹配，会最终匹配到路由 ```  match "*path", to: "home#error_404", via: :all ``` 去
方案：
URL 做图路由中正则表达式增加横线 ```path: /[\w\d\.\/\-]+/i```
> Fix: 本地文件上传，URL做图路路由错误

- app/assets/javascripts/editor.coffee
目前，可以传 js 文件 eg: https://l.ruby-china.com/photo/2018/e8af7717-3702-4f0a-9617-d4a56861cec2.js
> 屏蔽非图片文件的上传

- app/views/replies/create.js.erb
https://github.com/ruby-china/homeland/blob/f402be00446cd1a269baf8feb74e7ec0be24a65d/app/controllers/replies_controller.rb#L18
view 内用 ``` j ``` 后 ``` <br/>```  会被替换为 ```  &lt;br/&gt;  ``` 原样显示在页面上。
> FixBug, 显示逻辑不匹配

- app/assets/stylesheets/toc.scss
issue #1081
在移动设备下，文章的目录按钮点击后，列表无法正常显示.
原因是列表的上层div 限制了
```css
height: 100%;
max-height: 100%;
```
修改为
```css
height: auto;
max-height: none;
```
可以显示完整的列表
> 修复移动设备下，文章的目录无法正常显示的问题

- app/views/notifications/notifications/_notification.html.erb
remove the useless equal-sign, which will render a empty newline in html source
> remove the useless equal-sign

- app/models/location.rb
热门城市不应该出现 users_count: 0 的城市，否则，点击会出现not page
> fix hot locations scope

- config/initializers/rucaptcha.rb
原始代码只有
```ruby
config.api_server_url = "https://recaptcha.net/recaptcha/api.js"
```
此代码在国内可以正常显示，但无法验证。现在又增加了：
```ruby
config.verify_url = "https://recaptcha.net/recaptcha/api/siteverify"
```
> 解决了Recaptcha在国内访问，无法验证的问题

- app/controllers/application_controller.rb
rails 5.1 开始不支持 ``` nothing: true ```的写法
会导致 ```ActionView::MissingTemplate``` 错误 , 
例如访问: https://ruby-china.org/abc/38901.php
ref: https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_controller/metal/rendering.rb#L102
由于 exception-track 忽略了 ```ActionView::MissingTemplate```，所以后台看不到这个错误记录
https://github.com/ruby-china/homeland/blob/master/config/initializers/exception-track.rb#L14
但在 NewRelic 里可以抓到好多这个错误，都是爬虫爬过来的。
> Fix ActionView::MissingTemplate

- Dockerfile-base
If we want to install acme.sh by 
```
curl https://get.acme.sh | sh
```
we also need
**cron**
**socat(Optional)**
Otherwise, the commend *RUN curl https://get.acme.sh | sh* will not be run. `acme.sh` can be absent, while running `sudo make install_ssl`.
>  feat: Append missing denpendencies.

- app/javascript/front/topics.js
While submitting reply by `Command + Enter`, I will get this error
>  hotfix: Fix 406 issue while submiting reply by key combinations.

- app/javascript/homeland/index.scss
暗黑模式下 textarea 的调整大小的滑块仍为白色。
修改前：
修改后：
> Style the resize grabber of textarea

- app/controllers/admin/users_controller.rb
While updating Team instance in Admin panel, I got this exception:
>  hotfix: Fix `nil` issue while updating Team instance in admin panel.

- Gemfile
- Gemfile.lock
去年带了[一个实习生做的这个项目](https://github.com/Xu-Zhiqing/jieba_rb)，已经升级到cppjieba 5.0.0，相比原版，支持自定义字典。
> Bump to new jieba-rb which based on cppjieba v5.0.0

- app/controllers/teams_controller.rb
- 当含有非法字符串时，user_path 报错
- 当改为已存在的login时，user_path 错误，操作时提示无权限访问
>  fix: link to right path when login of team was update failed

- app/javascript/homeland/markdown.scss
编辑器输入代码之后点击预览，会出现超框现象。
话说这里为什么之前是 -25px。
修改之后：
> Fix markdown code preview overflow

- app/controllers/application_controller/localize.rb
- app/views/layouts/application.html.erb
忘了考虑设置里的 `Setting.auto_locale` 了。
> Fix I18n auto_locale for JavaScript

- Gemfile.lock
/home/runner/work/homeland/homeland/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/compile_cache/iseq.rb:13:in `to_binary': wrong argument type false (expected Symbol) (TypeError)
> bundle update bootsnap to fix for ruby 3.0.3:

- app/javascript/homeland/index.scss
> Fix text color of search input in dark mode

- app/javascript/homeland/bootstrap_custom.scss
- package.json
- yarn.lock
Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
[The import sequence do matter](https://stackoverflow.com/a/76993430/262826)
> Bump bootstrap to avoid autoprefixer warning:

- package.json
- yarn.lock
.card-body { color: var(--bs-card-color); }
https://github.com/twbs/bootstrap/issues/38852
In PR #1411, we bumped to bootstrap 5.3, but it will lead Post content text not work in dark mode. (original dark:text-gray-100, but overwrite by card-body color)
> Need downgrade to 5.2.3 because 5.3 introduce .card-body color

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .gitignore
- Gemfile.lock
- Procfile.dev
- bin/dev
- test/controllers/api/nodes_test.rb
- test/models/reply_test.rb
添加了 devcontainer 配置，用 vscode 或者其他支持 devcontainer 的编辑器/IDE 打开，在弹出提示中选择在容器中打开，进入命令行后用 `bin/dev` 即可启动服务。
不过目前有个问题，app 镜像需要设置 `platform: linux/amd64`，这在 mac 或者 windows 环境下会有性能损失。
这是因为 https://github.com/huacnlee/rucaptcha 这个 gem 缺少预编译平台：
```
- aarch64-linux-musl
```
另外 nokogiri 在 alpine 需要添加依赖 `apk add gcompat`。
看能不能给 rucaptcha 加上 `aarch64-linux-musl`，然后我再更新 PR。
> Add devcontainer
